"use client";

import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";

const fishTable = {
  ilios: [
      { name: "파치마리 복어", rarity: "일반", color: "text-zinc-300" },
          { name: "루시우 개구리어", rarity: "희귀", color: "text-sky-300" },
              { name: "라인하르트 방벽 거북어", rarity: "에픽", color: "text-purple-300" },
                ],

                  hanamura: [
                      { name: "키리코 여우 금붕어", rarity: "희귀", color: "text-pink-300" },
                          { name: "시마다 백룡어", rarity: "에픽", color: "text-violet-300" },
                              { name: "한조 쌍룡 황제어", rarity: "전설", color: "text-orange-300" },
                                ],

                                  busan: [
                                      { name: "부산 황금 참치", rarity: "희귀", color: "text-sky-300" },
                                          { name: "디바 네오나 쥐가오리", rarity: "에픽", color: "text-fuchsia-300" },
                                              { name: "부산 전설 황금 상어", rarity: "전설", color: "text-yellow-300" },
                                                ],

                                                  null_sector: [
                                                      { name: "널 섹터 기계 상어", rarity: "에픽", color: "text-red-300" },
                                                          { name: "옴닉 크라켄 신화", rarity: "신화", color: "text-rose-300" },
                                                              { name: "✨ 옴닉 창조주 초월체", rarity: "초월", color: "text-cyan-200" },
                                                                ],
                                                                };

                                                                const regionNames: Record<string, string> = {
                                                                  ilios: "일리오스 우물",
                                                                    hanamura: "하나무라 정원 연못",
                                                                      route66: "66번 국도 오아시스",
                                                                        busan: "부산 해변",
                                                                          numbani: "눔바니 강 하류",
                                                                            antarctica: "아나타크틱 연구소",
                                                                              horizon: "호라이즌 달 식민지",
                                                                                null_sector: "널 섹터 심연",
                                                                                };

                                                                                export default function FishingPage() {
                                                                                  const searchParams = useSearchParams();

                                                                                    const region = searchParams.get("region") || "ilios";

                                                                                      const currentFish = useMemo(() => {
                                                                                          const table =
                                                                                                fishTable[region as keyof typeof fishTable] || fishTable.ilios;

                                                                                                    return table[Math.floor(Math.random() * table.length)];
                                                                                                      }, [region]);

                                                                                                        const [result, setResult] = useState<null | {
                                                                                                            name: string;
                                                                                                                rarity: string;
                                                                                                                    color: string;
                                                                                                                      }>(null);

                                                                                                                        const [loading, setLoading] = useState(false);

                                                                                                                          function startFishing() {
                                                                                                                              setLoading(true);
                                                                                                                                  setResult(null);

                                                                                                                                      setTimeout(() => {
                                                                                                                                            setResult(currentFish);
                                                                                                                                                  setLoading(false);
                                                                                                                                                      }, 2500);
                                                                                                                                                        }

                                                                                                                                                          return (
                                                                                                                                                              <main className="relative min-h-screen overflow-hidden bg-slate-950 text-white">
                                                                                                                                                                    {/* 배경 */}
                                                                                                                                                                          <div className="absolute inset-0 bg-gradient-to-b from-cyan-900/30 via-slate-950 to-black" />

                                                                                                                                                                                {/* 물결 효과 */}
                                                                                                                                                                                      <div className="absolute bottom-0 left-0 h-64 w-full bg-cyan-400/10 blur-3xl" />

                                                                                                                                                                                            <section className="relative z-10 mx-auto flex min-h-screen max-w-3xl flex-col items-center justify-center px-5 text-center">
                                                                                                                                                                                                    
                                                                                                                                                                                                            <a
                                                                                                                                                                                                                      href="/regions"
                                                                                                                                                                                                                                className="absolute left-5 top-5 rounded-xl border border-white/10 bg-white/10 px-4 py-2 text-sm font-bold"
                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                  ← 지역 선택
                                                                                                                                                                                                                                                          </a>

                                                                                                                                                                                                                                                                  <div className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-5 py-2 text-sm font-bold text-cyan-200">
                                                                                                                                                                                                                                                                            🎣 현재 지역
                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                            <h1 className="mt-5 text-5xl font-black">
                                                                                                                                                                                                                                                                                                      {regionNames[region] || "일리오스 우물"}
                                                                                                                                                                                                                                                                                                              </h1>

                                                                                                                                                                                                                                                                                                                      <p className="mt-4 max-w-xl text-slate-300">
                                                                                                                                                                                                                                                                                                                                찌를 던지고 전설의 물고기를 낚아보세요.
                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                {/* 낚시 영역 */}
                                                                                                                                                                                                                                                                                                                                                        <div className="mt-12 flex h-72 w-full items-center justify-center rounded-[40px] border border-cyan-300/20 bg-gradient-to-b from-cyan-500/20 to-blue-950/40 shadow-2xl">
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                            {!loading && !result && (
                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-7xl">🎣</div>

                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-5 text-xl font-bold text-cyan-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                    찌를 던질 준비 완료
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-center animate-pulse">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-7xl">🌊</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-5 text-2xl font-black text-cyan-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          입질이 오는 중...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {result && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-7xl">🐟</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className={`mt-5 text-3xl font-black ${result.color}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {result.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="mt-2 text-xl text-yellow-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {result.rarity}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-6 rounded-2xl bg-white/10 px-5 py-3 text-lg font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ✨ 포획 성공!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 버튼 */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={startFishing}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="mt-10 rounded-2xl bg-cyan-400 px-10 py-5 text-2xl font-black text-slate-950 shadow-lg shadow-cyan-400/30 transition hover:scale-105 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? "낚시 중..." : "🎣 낚시 시작"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }