"use client";

import { Suspense, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

const fishTable = {
  ilios: [
      { name: "파치마리 복어", rarity: "일반", color: "text-zinc-300" },
          { name: "루시우 개구리어", rarity: "희귀", color: "text-sky-300" },
              { name: "라인하르트 방벽 거북어", rarity: "에픽", color: "text-purple-300" },
                ],
                  hanamura: [
                      { name: "키리코 여우 금붕어", rarity: "희귀", color: "text-pink-300" },
                          { name: "시마다 백룡어", rarity: "에픽", color: "text-violet-300" },
                              { name: "한조 쌍룡 황제어", rarity: "전설", color: "text-orange-300" },
                                ],
                                  route66: [
                                      { name: "사막 메기", rarity: "일반", color: "text-zinc-300" },
                                          { name: "캐시디 석양 농어", rarity: "희귀", color: "text-orange-300" },
                                              { name: "솜브라 EMP 투명 상어", rarity: "전설", color: "text-yellow-300" },
                                                ],
                                                  busan: [
                                                      { name: "부산 황금 참치", rarity: "희귀", color: "text-sky-300" },
                                                          { name: "디바 네오나 쥐가오리", rarity: "에픽", color: "text-fuchsia-300" },
                                                              { name: "부산 전설 황금 상어", rarity: "전설", color: "text-yellow-300" },
                                                                ],
                                                                  numbani: [
                                                                      { name: "오리사 수호자 메기", rarity: "희귀", color: "text-green-300" },
                                                                          { name: "라마트라 공허 뱀장어", rarity: "에픽", color: "text-purple-300" },
                                                                              { name: "눔바니 자유 황제 나일어", rarity: "전설", color: "text-yellow-300" },
                                                                                ],
                                                                                  antarctica: [
                                                                                      { name: "남극 황제 대구", rarity: "희귀", color: "text-sky-200" },
                                                                                          { name: "남극 심해 킹크랩어", rarity: "에픽", color: "text-purple-300" },
                                                                                              { name: "윈스턴 원시 신화 고래", rarity: "신화", color: "text-rose-300" },
                                                                                                ],
                                                                                                  horizon: [
                                                                                                      { name: "달 저중력 부레어", rarity: "희귀", color: "text-indigo-300" },
                                                                                                          { name: "호라이즌 진공 가오리", rarity: "에픽", color: "text-purple-300" },
                                                                                                              { name: "달빛 신화 수정 용왕어", rarity: "신화", color: "text-rose-300" },
                                                                                                                ],
                                                                                                                  null_sector: [
                                                                                                                      { name: "널 섹터 기계 상어", rarity: "에픽", color: "text-red-300" },
                                                                                                                          { name: "옴닉 크라켄 신화", rarity: "신화", color: "text-rose-300" },
                                                                                                                              { name: "✨ 옴닉 창조주 초월체", rarity: "초월", color: "text-cyan-200" },
                                                                                                                                ],
                                                                                                                                };

                                                                                                                                const regionNames: Record<string, string> = {
                                                                                                                                  ilios: "일리오스 우물",
                                                                                                                                    hanamura: "하나무라 정원 연못",
                                                                                                                                      route66: "66번 국도 오아시스",
                                                                                                                                        busan: "부산 해변",
                                                                                                                                          numbani: "눔바니 강 하류",
                                                                                                                                            antarctica: "아나타크틱 연구소",
                                                                                                                                              horizon: "호라이즌 달 식민지",
                                                                                                                                                null_sector: "널 섹터 심연",
                                                                                                                                                };

                                                                                                                                                type Fish = {
                                                                                                                                                  name: string;
                                                                                                                                                    rarity: string;
                                                                                                                                                      color: string;
                                                                                                                                                      };

                                                                                                                                                      function FishingContent() {
                                                                                                                                                        const searchParams = useSearchParams();
                                                                                                                                                          const region = searchParams.get("region") || "ilios";

                                                                                                                                                            const currentFish = useMemo(() => {
                                                                                                                                                                const table = fishTable[region as keyof typeof fishTable] || fishTable.ilios;
                                                                                                                                                                    return table[Math.floor(Math.random() * table.length)];
                                                                                                                                                                      }, [region]);

                                                                                                                                                                        const [result, setResult] = useState<Fish | null>(null);
                                                                                                                                                                          const [loading, setLoading] = useState(false);

                                                                                                                                                                            function startFishing() {
                                                                                                                                                                                setLoading(true);
                                                                                                                                                                                    setResult(null);

                                                                                                                                                                                        setTimeout(() => {
                                                                                                                                                                                              setResult(currentFish);
                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                        }, 2500);
                                                                                                                                                                                                          }

                                                                                                                                                                                                            return (
                                                                                                                                                                                                                <main className="relative min-h-screen overflow-hidden bg-slate-950 text-white">
                                                                                                                                                                                                                      <div className="absolute inset-0 bg-gradient-to-b from-cyan-900/30 via-slate-950 to-black" />
                                                                                                                                                                                                                            <div className="absolute bottom-0 left-0 h-64 w-full bg-cyan-400/10 blur-3xl" />

                                                                                                                                                                                                                                  <section className="relative z-10 mx-auto flex min-h-screen max-w-3xl flex-col items-center justify-center px-5 text-center">
                                                                                                                                                                                                                                          <a
                                                                                                                                                                                                                                                    href="/regions"
                                                                                                                                                                                                                                                              className="absolute left-5 top-5 rounded-xl border border-white/10 bg-white/10 px-4 py-2 text-sm font-bold"
                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                ← 지역 선택
                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                <div className="rounded-full border border-cyan-300/30 bg-cyan-300/10 px-5 py-2 text-sm font-bold text-cyan-200">
                                                                                                                                                                                                                                                                                                          🎣 현재 지역
                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                          <h1 className="mt-5 text-5xl font-black">
                                                                                                                                                                                                                                                                                                                                    {regionNames[region] || "일리오스 우물"}
                                                                                                                                                                                                                                                                                                                                            </h1>

                                                                                                                                                                                                                                                                                                                                                    <p className="mt-4 max-w-xl text-slate-300">
                                                                                                                                                                                                                                                                                                                                                              찌를 던지고 전설의 물고기를 낚아보세요.
                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-12 flex h-72 w-full items-center justify-center rounded-[40px] border border-cyan-300/20 bg-gradient-to-b from-cyan-500/20 to-blue-950/40 shadow-2xl">
                                                                                                                                                                                                                                                                                                                                                                                        {!loading && !result && (
                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-7xl">🎣</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-5 text-xl font-bold text-cyan-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                찌를 던질 준비 완료
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="animate-pulse text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-7xl">🌊</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-5 text-2xl font-black text-cyan-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      입질이 오는 중...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {result && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-7xl">🐟</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className={`mt-5 text-3xl font-black ${result.color}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {result.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="mt-2 text-xl text-yellow-300">{result.rarity}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-6 rounded-2xl bg-white/10 px-5 py-3 text-lg font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ✨ 포획 성공!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={startFishing}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mt-10 rounded-2xl bg-cyan-400 px-10 py-5 text-2xl font-black text-slate-950 shadow-lg shadow-cyan-400/30 transition hover:scale-105 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "낚시 중..." : "🎣 낚시 시작"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default function FishingPage() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Suspense fallback={<div className="min-h-screen bg-slate-950 text-white">로딩 중...</div>}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <FishingContent />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Suspense>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }